kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Release.Name }}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Release.Name }}\")].image"}]'
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
        deployment: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}
          configMap:
            name: {{ .Release.Name }}
            defaultMode: 420
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: TZ
              value: Europe/Stockholm
            - name: LANG
              value: sv_SE.utf8
            - name: JAVA_OPTS_APPEND
              value: '-Djboss.bind.address=0.0.0.0 -Dspring.config.location=file:/home/default/resource/application.yml'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: {{ .Release.Name }}
              mountPath: /home/default/resource
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Release.Name }}'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 600
