server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - uri: ${quarkus.headless.url}
          predicates:
            - Path=/hello-resteasy
logging:
  level:
    root: INFO

quarkus:
  headless:
    url: http://code-with-quarkus-headless.test-headless.svc:8081
