server:
  port: 8080
spring:
  cloud:
    kubernetes:
      discovery:
        namespaces[0]: quarkus-test
      loadbalancer:
        enabled: true
        mode: POD
    gateway:
      httpclient:
        connect-timeout: 250
      routes:

        ## HELLO URI
        - uri: ${quarkus.headless.url}
          predicates:
            - Path=/hello
          filters:
#            - name: Retry
#              args:
#                retries: 5
#                statuses: BAD_GATEWAY
#                methods: GET,POST
#                backoff:
#                  firstBackoff: 10ms
#                  maxBackoff: 50ms
#                  factor: 2
#                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: helloCircuitBreaker
                fallbackUri: forward:/fallback/hello
                statusCodes:
                  - "BAD_GATEWAY"
        - uri: ${quarkus.fallback.url}
          predicates:
            - Path=/fallback/hello
          filters:
            - StripPrefix=1

        ## WORLD URI
        - uri: ${quarkus.headless.url}
          predicates:
            - Path=/world
          filters:
            - name: CircuitBreaker
              args:
                name: worldCircuitBreaker
                fallbackUri: forward:/fallback/world
                statusCodes:
                  - "BAD_GATEWAY"
        - uri: ${quarkus.fallback.url}
          predicates:
            - Path=/fallback/world
          filters:
            - StripPrefix=1
                  
logging:
  level:
    root: INFO
    reactor:
      netty:
        http:
          client:
            HttpClientConnect: DEBUG

quarkus:
  headless:
     url:  lb://quarkus-test-headless
  fallback:
     url: http://quarkus-test.quarkus-test.svc:8080
