server:
  port: 8080
spring:
  cloud:
    kubernetes:
      loadbalancer:
        enabled: true
        mode: POD
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - uri: ${quarkus.headless.url}
          predicates:
            - Path=/hello
logging:
  level:
    root: DEBUG

quarkus:
  headless:
     url:  lb://quarkus-test-headless
