server:
  port: 8080
spring:
  cloud:
    kubernetes:
      discovery:
        namespaces[0]: quarkus-test
      loadbalancer:
        enabled: true
        mode: POD
    gateway:
      httpclient:
        connect-timeout: 250
      routes:
        - uri: ${quarkus.headless.url}
          predicates:
             - Path=/api/{*segments}
          filters:
            - name: CircuitBreaker
              args:
                name: apiCircuitBreaker
                fallbackUri: forward:/fallback/api/{segments}
                statusCodes:
                  - "BAD_GATEWAY"
        - uri: ${quarkus.fallback.url}
          predicates:
            - Path=/fallback/api/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 5
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
                  
logging:
  level:
    root: INFO
    reactor:
      netty:
        http:
          client:
            HttpClientConnect: DEBUG

quarkus:
  headless:
     url:  lb://quarkus-test-headless
  fallback:
     url: http://quarkus-test.quarkus-test.svc:8080
